### PR TITLE
Fix structure overflow

### LINKED ISSUE #65: Table on organisation structure breaks the page on mobile
picrel

### PR DESCRIPTION
**Pull request by Rei-x**
Closes #65

### CODE REVIEW

File: frontend/src/components/Navbar.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export const Navbar = () => {
   const router = useRouter();
 
   return (
-    <Box mb={16} w="100%" px={16}>
+    <Box mb={16} w="100%" px={[{ base: 0, md: 16 }]}>
```
Comment (Omikorin) [inline frontend/src/components/Navbar.tsx]: fix typings

**Review by Omikorin — CHANGES_REQUESTED** [review]

**Review by Omikorin — APPROVED** [review]
